# Generated by Django 4.0 on 2022-01-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='other_features',
            field=models.TextField(null=True),
        ),
    ]
